### ISSUE TITLE
shower-event.py is NOK if it is called outside its directory

### ISSUE THREAD

**Issue by luckyjim** [grand-mother/grand#28]
Very stange:
```
grand/examples/simulation$ python shower-event.py
grand/examples/simulation$ echo $?
0

```
so OK, but 
```
/grand$ python examples/simulation/shower-event.py 
/grand$ echo $?
1

```
NOK ?

error:
```
Traceback (most recent call last):
  File "examples/simulation/shower-event.py", line 31, in <module>
    shower = ShowerEvent.load(showerdir)
  File "/home/jcolley/projet/grand_wk/noAppIm/grand/grand/simulation/shower/generic.py", line 117, in load
    self = load(source)
  File "/home/jcolley/projet/grand_wk/noAppIm/grand/grand/simulation/shower/generic.py", line 127, in _from_datafile
    with io.open(path) as root:
  File "/home/jcolley/projet/grand_wk/noAppIm/grand/grand/io.py", line 477, in open
    f = _File(file, mode)
  File "/home/jcolley/install/miniconda3/envs/gd_test2/lib/python3.8/site-packages/h5py/_hl/files.py", line 507, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/home/jcolley/install/miniconda3/envs/gd_test2/lib/python3.8/site-packages/h5py/_hl/files.py", line 220, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 106, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = '../../tests/simulation/data/zhaires', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

```

**Comment by luckyjim** [comment]
problem is here

https://github.com/grand-mother/grand/blob/dev/grand/simulation/shower/generic.py#L86
add message debug

```
            logger.debug(type(source))
            logger.debug(source)
            logger.debug(source.is_dir())
            if source.is_dir():
```

log debug when ok
```
13:04:21.532  INFO [grand.examples.simulation.shower-event 27] 
13:04:21.532 DEBUG [grand.simulation.shower.generic 86] <class 'pathlib.PosixPath'>
13:04:21.532 DEBUG [grand.simulation.shower.generic 87] ../../tests/simulation/data/zhaires
13:04:21.532 DEBUG [grand.simulation.shower.generic 88] True
13:04:21.533  INFO [grand.simulation.shower.generic 105] Loading shower data from ../../tests/simulation/data/zhaires:/
```

when nok
```
13:04:10.622 DEBUG [grand.simulation.shower.generic 86] <class 'pathlib.PosixPath'>
13:04:10.622 DEBUG [grand.simulation.shower.generic 87] ../../tests/simulation/data/zhaires
13:04:10.622 DEBUG [grand.simulation.shower.generic 88] False
13:04:10.622  INFO [grand.simulation.shower.generic 105] Loading shower data from ../../tests/simulation/data/zhaires:/

```

but why ?

**Comment by niess** [comment]
Jean-Marc,

to me, the problem is that this example uses a fixed relative path for the antenna's data, assuming that the script is always called from a given location. At this [line](https://github.com/grand-mother/grand/blob/master/examples/simulation/shower-event.py#L17). When called from another location, then the path is invalid, it points to nothing. Thus, `is_dir` would return `False`.

In order that the script would work from any location, one would need to use a path relative to the script location, e.g. prepending the path with a directory name extracted from `__file__`.

I didn't want to complicate the example. This is the reason why I used a fixed path. But, feel free to change :)

**Comment by luckyjim** [comment]
Hello Valentin,
Thank you for opening my eyes.
I will modify the definition of the path.

**Comment by luckyjim** [comment]
Fix in dev branch
