### ISSUE TITLE
convert_efield2voltage.py does not work for large antenna positions

### ISSUE THREAD

**Issue by jelenakhlr** [grand-mother/grand#64]
This seems to be due to efield2voltage.py, line 160: when antenna positions x,y,z are larger than 22 000 000, the program crashes.

**Comment by jelenakhlr** [comment]
This problem is still not fixed

Traceback (most recent call last):
  File "/home/grand/sim2root/CoREASRawRoot/../../scripts/convert_efield2voltage.py", line 141, in <module>
    signal.compute_voltage()    # saves automatically
  File "/home/grand/grand/sim/efield2voltage.py", line 417, in compute_voltage
    self.compute_voltage_event(event_idx=evt_idx) # event_number and run_number is None
  File "/home/grand/grand/sim/efield2voltage.py", line 361, in compute_voltage_event
    self.compute_voc_event(event_idx, event_number, run_number)
  File "/home/grand/grand/sim/efield2voltage.py", line 301, in compute_voc_event
    self.compute_voc_du(du_idx)
  File "/home/grand/grand/sim/efield2voltage.py", line 247, in compute_voc_du
    self.get_leff(du_idx)
  File "/home/grand/grand/sim/efield2voltage.py", line 159, in get_leff
    raise ValueError("du_pos_x is too large for computing!")

**Comment by jelenakhlr** [comment]
I will try again with better sim examples, but this should not happen! Especially in our case, when we plan to have a GRAND detector array ;)

**Comment by jelenakhlr** [comment]
There was a unit conversion error that I fixed a while back. This problem has not occurred since then, so I will close this issue for now!
